### ISSUE TITLE
CommandType

### ISSUE THREAD

**Issue by nahilep** [RanvierMUD/core#65]
I feel that `CommandType` is no longer of any meaning in core. It's _used_ twice in core. Once for defaulting a command without type in `Command` constructor and in `BundleManager` it gets imported, but I can't see it being used.

Proposal:
* leave it in core, but deprecate it
* remove unnecessary import in BundleManager
* change default in `Command` constructor to ~a harcoded `Symbol("COMMAND")`~ null
* add the exact same file to `bundle-example-lib` and update `CommandParser` and `bundle-example-input-events/input-events/commands.js` to use this

**Comment by shawncplus** [comment]
> change default in Command constructor to a harcoded Symbol("COMMAND")

Because a `Symbol` is globally unique you could never use that value to compare against in a `switch` or an `if` because `Symbol("COMMAND") !== Symbol("COMMAND")` The `"COMMAND"` there is purely for debugging purposes both will actually be entirely unique symbols

**Comment by nahilep** [comment]
I feared something like that, but I am not familiar with Symbols and didn't want to look into it. I think this should still be doable. How about: Symbol('UNSET') if it is unset?

**Comment by shawncplus** [comment]
heh the point is that if you directly assign a `Symbol` to `Command.type` you _never_ have a value to compare it to because it is perfectly unique so you wouldn't even be able to detect if it's unset. It'd be better to just use `null` in that case.

The point of using a `Symbol` enum is that you have the enum to compare against. I'm not against the idea of deprecating it but it's pretty low priority for me because you are free to set type to any value you wish and the core won't get in your way

**Comment by shawncplus** [comment]
This doesn't really need a "fix" anymore since the command parser is no longer in core and the only place `CommandType` is used it so set a default. Bundle devs are free to set it to any arbitrary value they wish
